import React,{useState} from 'react';
import {Clock,Check,Settings} from 'lucide-react';
import type {Episode,Obligation,FollowUpPolicy} from '../types';
import {post} from '../api';
import './follow-up.css';
const money=(n:number,c:string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:n%100?2:0}).format(n/100);
const when=(s:string)=>new Date(s).toLocaleString('en-IN',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
type ModalProps={title:string;close:()=>void;children:React.ReactNode};
export function FollowUp({e,o,me,busy,act,Modal}:{e:Episode;o:Obligation;me:string;busy:boolean;act:(f:()=>Promise<unknown>)=>Promise<void>;Modal:React.ComponentType<ModalProps>}){
 const [settings,setSettings]=useState(false),[waive,setWaive]=useState(false),[considerAgain,setConsiderAgain]=useState(false),[validation,setValidation]=useState('');const [p,setP]=useState(o.follow_up_policy);
 const [preset,setPreset]=useState([24,48,72,168].includes(p.minimum_interval_hours)?String(p.minimum_interval_hours):'custom');
 const [unit,setUnit]=useState('hours'),[custom,setCustom]=useState(p.minimum_interval_hours);
 const [maxPreset,setMaxPreset]=useState([1,2,3].includes(p.maximum)?String(p.maximum):'custom');
 const call=(action:string,policy?:FollowUpPolicy)=>act(async()=>{await post(`/episodes/${e.id}/obligations/${o.id}/follow-up`,{actor:me,action,...(policy?{policy}:{})});setSettings(false);setWaive(false);setConsiderAgain(false);});
 const component=e.components.find(c=>c.id===o.component_id)?.description||e.title;
 const resolved=['PAID','WAIVED'].includes(o.status),owner=me===o.creditor;
 const save=()=>{const hours=preset==='custom'?custom*(unit==='days'?24:1):Number(preset);if(!Number.isInteger(hours)||hours<1||hours>8760||!Number.isInteger(p.maximum)||p.maximum<1||p.maximum>10){setValidation('Choose a whole-number interval of 1–8760 hours and a maximum of 1–10 reminders.');return;}if(!p.quiet_start||!p.quiet_end||p.quiet_start===p.quiet_end){setValidation('Choose different start and end times for quiet hours.');return;}setValidation('');return call(o.follow_up_authorized==='AUTHORIZED'?'edit':'authorize',{...p,minimum_interval_hours:hours});};
 const open=()=>{setValidation('');setP(o.follow_up_policy);setPreset([24,48,72,168].includes(o.follow_up_policy.minimum_interval_hours)?String(o.follow_up_policy.minimum_interval_hours):'custom');setCustom(o.follow_up_policy.minimum_interval_hours);setUnit('hours');setMaxPreset([1,2,3].includes(o.follow_up_policy.maximum)?String(o.follow_up_policy.maximum):'custom');setSettings(true);};
 return <div className="follow-up" aria-label={`${o.debtor} ${component} follow-up`}>
  <div className="follow-up-heading"><strong>{component}</strong><span>{o.status==='PAID'?<><Check size={13}/> All settled</>:o.status==='WAIVED'?'Let go · waived':`${money(o.amount_remaining,e.currency)} ${owner?'owes you':'remaining'}`}</span></div>
  {!resolved&&<><div className="follow-up-meta"><span>Follow-up <strong>{o.follow_up_authorized==='AUTHORIZED'&&e.reminder_policy.enabled&&o.status!=='DISPUTED'&&!o.follow_up_escalated?'ON':'OFF'}</strong> · {o.follow_up_authorized==='PAUSED'?'Paused':o.follow_up_authorized==='DECLINED'?'You’re handling this':o.follow_up_authorized==='NOT_DECIDED'?'Your choice':`${o.reminder_count}/${o.follow_up_policy.maximum} reminders`}</span>{o.next_check_at&&<small><Clock size={12}/>Next check · {when(o.next_check_at)}</small>}{o.follow_up_escalated&&<small>Reminder limit reached · over to you</small>}</div>
  {owner&&o.status!=='UNCONFIRMED'&&o.follow_up_authorized==='NOT_DECIDED'&&(!o.follow_up_deferred||considerAgain)&&<><p>Want Owedience to follow this up for you?</p><div className="button-row"><button className="button primary small-button" disabled={busy||o.status==='DISPUTED'} onClick={open}>Yes, handle the follow-up</button><button className="button small-button" disabled={busy} onClick={()=>call('decline')}>No, I’ll handle it myself</button><button className="text-link" disabled={busy} onClick={()=>call('defer')}>Not now</button></div></>}
  {owner&&o.follow_up_authorized==='NOT_DECIDED'&&o.follow_up_deferred&&!considerAgain&&o.status!=='UNCONFIRMED'&&<button className="text-link" disabled={busy} onClick={()=>setConsiderAgain(true)}>Decide on follow-up</button>}
  {owner&&o.reminder_approval&&!o.reminder_approval.approved_at&&<div className="follow-up-approval"><p>{o.reminder_approval.message}</p><div className="button-row"><button className="button primary small-button" disabled={busy} onClick={()=>call('approve')}>Send it</button><button className="button small-button" disabled={busy} onClick={()=>call('snooze')}>Not now</button><button className="text-link" disabled={busy} onClick={()=>call('decline')}>Stop reminders</button></div></div>}
  {owner&&o.reminder_count>0&&o.follow_up_authorized==='AUTHORIZED'&&o.follow_up_policy.reminder_approval_mode==='ASK_EACH_TIME'&&!o.future_autonomy_decided&&<div className="follow-up-approval"><p>Should I handle future reminders automatically within these limits?</p><div className="button-row"><button className="button small-button" disabled={busy} onClick={()=>call('edit',{...o.follow_up_policy,reminder_approval_mode:'ASK_FIRST_THEN_AUTO'})}>Yes</button><button className="text-link" disabled={busy} onClick={()=>call('edit',{...o.follow_up_policy,reminder_approval_mode:'ASK_EACH_TIME'})}>Ask me each time</button></div></div>}
  {owner&&<div className="button-row follow-up-actions">{o.follow_up_authorized==='AUTHORIZED'&&<><button className="text-link" disabled={busy} onClick={()=>act(()=>post(`/episodes/${e.id}/continue`))}>Send reminder now</button><button className="text-link" disabled={busy} onClick={()=>call('pause')}>Pause reminders</button><button className="text-link" disabled={busy} onClick={open}><Settings size={13}/>Settings</button></>}{o.follow_up_authorized==='PAUSED'&&<button className="text-link" disabled={busy||o.status==='DISPUTED'} onClick={()=>call('resume')}>Resume follow-up</button>}{o.follow_up_authorized==='DECLINED'&&o.status!=='UNCONFIRMED'&&<button className="text-link" disabled={busy||o.status==='DISPUTED'} onClick={open}>Authorize follow-up</button>}<button className="text-link" disabled={busy} onClick={()=>setWaive(true)}>Let it go</button></div>}
  {owner&&o.follow_up_authorized==='AUTHORIZED'&&<small className="muted">{o.follow_up_policy.minimum_interval_hours}h interval · {o.follow_up_policy.reminder_approval_mode==='ASK_EACH_TIME'?'Ask each time':o.follow_up_policy.reminder_approval_mode==='ASK_FIRST_THEN_AUTO'?'Ask first, then automatic':'Automatic within limits'} · Quiet {o.follow_up_policy.quiet_start}–{o.follow_up_policy.quiet_end}{o.reminder_eligibility&&!o.reminder_eligibility.eligible&&<> · {o.reminder_eligibility.reason}</>}</small>}
  </>}
  {owner&&waive&&<Modal title={`Stop following up on ${o.debtor}’s ${money(o.amount_remaining,e.currency)}?`} close={()=>setWaive(false)}><p className="muted">This share will be waived. The financial history stays; it won’t be recorded as paid.</p><div className="button-row"><button className="button primary" disabled={busy} onClick={()=>call('waive')}>Yes, let it go</button><button className="button" onClick={()=>setWaive(false)}>Cancel</button></div></Modal>}
  {owner&&settings&&<Modal title="How should I follow up?" close={()=>setSettings(false)}><div className="follow-up-settings"><p className="muted">Only {o.debtor}’s {component} share. You decide who Owedience may follow up with.</p><label>Reminder frequency<select className="input" value={preset} onChange={x=>{setPreset(x.target.value);if(x.target.value!=='custom')setP({...p,minimum_interval_hours:Number(x.target.value),...(x.target.value==='24'?{maximum:1}:{})});if(x.target.value==='24')setMaxPreset('1');}}><option value="24">Once after 24 hours</option><option value="48">Every 2 days</option><option value="72">Every 3 days</option><option value="168">Once a week</option><option value="custom">Custom</option></select></label>{preset==='custom'&&<div className="form-grid"><label>Every<input className="input" type="number" min="1" max={unit==='days'?365:8760} value={custom} onChange={x=>setCustom(Number(x.target.value))}/></label><label>Unit<select className="input" value={unit} onChange={x=>setUnit(x.target.value)}><option value="hours">hours</option><option value="days">days</option></select></label></div>}
   <label>Maximum reminders<select className="input" value={maxPreset} onChange={x=>{setMaxPreset(x.target.value);if(x.target.value!=='custom')setP({...p,maximum:Number(x.target.value)});}}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="custom">Custom</option></select></label>{maxPreset==='custom'&&<label>Custom maximum (1–10)<input className="input" type="number" min="1" max="10" value={p.maximum} onChange={x=>setP({...p,maximum:Number(x.target.value)})}/></label>}
   <label>Before reminders<select className="input" value={p.reminder_approval_mode} onChange={x=>setP({...p,reminder_approval_mode:x.target.value as FollowUpPolicy['reminder_approval_mode']})}><option value="ASK_EACH_TIME">Ask me first · ask each time</option><option value="ASK_FIRST_THEN_AUTO">Ask before first, then automatic within limits</option><option value="AUTO_WITHIN_LIMITS">Send automatically using these rules</option></select></label>
   <div className="form-grid"><label>Don’t message between<input className="input" type="time" value={p.quiet_start} onChange={x=>setP({...p,quiet_start:x.target.value})}/></label><label>And<input className="input" type="time" value={p.quiet_end} onChange={x=>setP({...p,quiet_end:x.target.value})}/></label></div><label>Time zone<select className="input" value={p.utc_offset_minutes} onChange={x=>setP({...p,utc_offset_minutes:Number(x.target.value)})}>{[...new Set([330,0,-300,60,p.utc_offset_minutes])].map(n=><option key={n} value={n}>UTC {n>=0?'+':'−'}{String(Math.floor(Math.abs(n)/60)).padStart(2,'0')}:{String(Math.abs(n)%60).padStart(2,'0')}</option>)}</select></label>
   <label>Tone<select className="input" value={p.tone} onChange={x=>setP({...p,tone:x.target.value as 'neutral'|'friendly'})}><option value="neutral">Neutral</option><option value="friendly">Friendly</option></select></label><label>Relationship context (optional)<input className="input" maxLength={200} value={p.relationship_context} onChange={x=>setP({...p,relationship_context:x.target.value})} placeholder="Only what you want used in reminders"/></label><p className="muted">Payments, disputes, quiet hours and limits always override permission. Scheduled checks wait until allowed; “Send reminder now” uses these same rules.</p><>{validation&&<p role="alert" className="error-banner">{validation}</p>}</><button className="button primary full" disabled={busy} onClick={save}>Save and authorize this follow-up</button></div></Modal>}
 </div>;
}
