import React, {useRef,useState} from 'react';
import {Plus,Minus,X,Mic,Upload,LoaderCircle,Receipt,ChevronDown} from 'lucide-react';

type FileInput={filename:string;mime_type:string;data_base64:string};
type BillItem={description:string;amount:string};
type Claim={consumers:string[];sharing:string;amounts:Record<string,string>;percentages:Record<string,string>};
type ModalProps={title:string;close:()=>void;children:React.ReactNode};
const categories=[['food_dining','🍽 Food & Dining'],['travel_transport','🚕 Travel & Transport'],['shopping','🛍 Shopping'],['accommodation','🏠 Stay / Accommodation'],['entertainment','🎬 Recreation & Entertainment'],['gifts','🎁 Gifts'],['groceries','🛒 Groceries'],['electronics','💻 Accessories / Electronics'],['delivery_orders','📦 Delivery / Orders'],['utilities','💡 Bills & Utilities'],['other','✏️ Other']];
const minor=(s:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(s))throw new Error('Use amounts with up to two decimal places.');const [a,b='']=s.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n<0||n>9_000_000_000_000)throw new Error('Please enter a valid amount.');return n;};
const readFile=(blob:Blob,filename:string):Promise<FileInput>=>new Promise((resolve,reject)=>{if(blob.size>10_000_000){reject(new Error('Choose a file smaller than 10 MB.'));return;}const reader=new FileReader();reader.onerror=()=>reject(new Error('Couldn’t read this file.'));reader.onload=()=>resolve({filename,mime_type:blob.type||'application/octet-stream',data_base64:String(reader.result).split(',')[1]});reader.readAsDataURL(blob);});

export function NewExpense({close,submit,busy,currentUser,Modal}:{close:()=>void;submit:(data:unknown)=>Promise<void>;busy:boolean;currentUser:string;Modal:React.ComponentType<ModalProps>}){
 const [title,setTitle]=useState('');const [category,setCategory]=useState('other');const [categoryDescription,setCategoryDescription]=useState('');const [people,setPeople]=useState([currentUser,'']);const [payerIndex,setPayerIndex]=useState(0);const [currency,setCurrency]=useState('INR');const [total,setTotal]=useState('');
 const [items,setItems]=useState<BillItem[]>([]);const [claims,setClaims]=useState<Record<number,Claim>>({});const [preference,setPreference]=useState('infer');const [rough,setRough]=useState<Record<string,string>>({});const [context,setContext]=useState('');const [extra,setExtra]=useState('');const [receipt,setReceipt]=useState<FileInput|null>(null);const [voice,setVoice]=useState<FileInput|null>(null);const [recording,setRecording]=useState(false);const [validation,setValidation]=useState('');
 const receiptRef=useRef<HTMLInputElement>(null);const voiceRef=useRef<HTMLInputElement>(null);const recorder=useRef<MediaRecorder|null>(null);const streamRef=useRef<MediaStream|null>(null);
 React.useEffect(()=>()=>{if(recorder.current?.state==='recording')recorder.current.stop();streamRef.current?.getTracks().forEach(t=>t.stop());},[]);
 const names=people.map(p=>p.trim()).filter(Boolean);const resize=(n:number)=>{if(n<1||n>30)return;setPeople(people.slice(0,n).concat(Array(Math.max(0,n-people.length)).fill('')));if(payerIndex>=n)setPayerIndex(0);setClaims({});};
 const updateClaim=(i:number,part:Partial<Claim>)=>setClaims({...claims,[i]:{...(claims[i]||{consumers:[],sharing:'unsure',amounts:{},percentages:{}}),...part}});
 const upload=async(file:File,kind:'receipt'|'voice')=>{try{const data=await readFile(file,file.name);kind==='receipt'?setReceipt(data):setVoice(data);setValidation('');}catch(e){setValidation((e as Error).message);}};
 const record=async()=>{try{if(recording){recorder.current?.stop();setRecording(false);return;}const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const r=new MediaRecorder(stream);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=x=>chunks.push(x.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());try{setVoice(await readFile(new Blob(chunks,{type:r.mimeType}),'Voice note.webm'));}catch(e){setValidation((e as Error).message);}};r.start();setRecording(true);}catch{setValidation('Voice recording isn’t available. You can upload a voice note or add text.');}};
 let discrepancy='';try{if(total&&items.length&&items.every(i=>i.description.trim()&&i.amount)){const sum=items.reduce((s,i)=>s+minor(i.amount),0);if(sum!==minor(total))discrepancy=`The items add up to ${new Intl.NumberFormat('en-IN',{style:'currency',currency}).format(sum/100)}, which differs from your total. Owedience will help check it; no amounts will be changed silently.`;}}catch{/* Form validation explains invalid input on submission. */}
 const save=async()=>{try{
  const participants=people.map(p=>p.trim());if(!title.trim()||participants.some(p=>!p))throw new Error('Add an expense name and a name for each person.');if(new Set(participants).size!==participants.length)throw new Error('Use a distinct name for each person.');const amount=minor(total);if(!amount)throw new Error('Add a positive bill total.');
  if(items.some(i=>!i.description.trim()||!i.amount||minor(i.amount)<=0))throw new Error('Add a name and positive amount for each bill item, or remove the empty item.');
  const components=items.map(i=>({description:i.description.trim(),amount:minor(i.amount)}));
  const proposed=Object.fromEntries(Object.entries(rough).filter(([p,n])=>participants.includes(p)&&n.trim()).map(([p,n])=>[p,minor(n)]));
  const assignments=Object.entries(claims).map(([index,c])=>({item_index:Number(index),consumers:c.consumers.filter(p=>participants.includes(p)),sharing:c.sharing,amounts:Object.fromEntries(Object.entries(c.amounts).filter(([p,n])=>c.consumers.includes(p)&&n.trim()).map(([p,n])=>[p,minor(n)])),percentages:Object.fromEntries(Object.entries(c.percentages).filter(([p,n])=>c.consumers.includes(p)&&n.trim()))}));
  setValidation('');await submit({title:title.trim(),payer:participants[payerIndex],participants,currency,total:amount,category,category_description:category==='other'?categoryDescription:'',components,initial_context:context,extra_context:extra,split_preference:preference,user_proposed_split:proposed,item_assignments:assignments,receipt,voice_note:voice});
 }catch(e){setValidation((e as Error).message);}};
 return <Modal title="What did you share?" close={close}><p className="muted">Start with what you know. Owedience will ask only for what’s missing.</p>{validation&&<p className="form-error" role="alert">{validation}</p>}
 <label>Expense name<input className="input" value={title} onChange={x=>setTitle(x.target.value)} placeholder="Dinner, airport cab, weekend groceries…"/></label><label>What was this for?<select className="input" value={category} onChange={x=>setCategory(x.target.value)}>{categories.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{category==='other'&&<label>Anything more specific? <small>Optional</small><input className="input" value={categoryDescription} onChange={x=>setCategoryDescription(x.target.value)} placeholder="A short description"/></label>}
 <div className="form-grid"><label>How much was the total?<input className="input" inputMode="decimal" value={total} onChange={x=>setTotal(x.target.value)} placeholder="0.00"/></label><label>Currency<select className="input" value={currency} onChange={x=>setCurrency(x.target.value)}>{['INR','USD','EUR','GBP'].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="input-file-row"><button className="button" onClick={()=>receiptRef.current?.click()}><Receipt size={15}/>Upload bill / receipt</button>{receipt&&<span><small>{receipt.filename}</small><button className="icon-button" aria-label="Remove receipt" onClick={()=>setReceipt(null)}><X size={14}/></button></span>}<input hidden ref={receiptRef} type="file" accept="image/*,application/pdf" onChange={x=>{const file=x.target.files?.[0];if(file)upload(file,'receipt');x.target.value='';}}/></div>{receipt&&<small className="muted">Your receipt will be saved as evidence. Add bill items if you know them; receipt reading is not available yet.</small>}
 <details className="input-details"><summary>Add bill items <small>Optional</small><ChevronDown size={14}/></summary><p className="muted">A whole bill is enough when everyone shared everything. Add items when different people shared different parts.</p>{items.map((c,i)=><div className="component-input" key={i}><input className="input" aria-label={`Item ${i+1} description`} placeholder="Bill item" value={c.description} onChange={x=>setItems(items.map((v,j)=>j===i?{...v,description:x.target.value}:v))}/><input className="input" aria-label={`Item ${i+1} amount`} placeholder="Amount" inputMode="decimal" value={c.amount} onChange={x=>setItems(items.map((v,j)=>j===i?{...v,amount:x.target.value}:v))}/><button className="icon-button" aria-label={`Remove item ${i+1}`} onClick={()=>{setItems(items.filter((_,j)=>j!==i));setClaims({});}}><X size={15}/></button></div>)}<button className="text-link" onClick={()=>setItems([...items,{description:'',amount:''}])}><Plus size={14}/>Add item</button>{discrepancy&&<p className="form-note">{discrepancy}</p>}</details>
 <label>How many people were involved?</label><div className="people-counter"><button className="button" aria-label="One fewer person" disabled={people.length===1} onClick={()=>resize(people.length-1)}><Minus size={14}/></button><strong>{people.length}</strong><button className="button" aria-label="One more person" disabled={people.length===30} onClick={()=>resize(people.length+1)}><Plus size={14}/></button></div><label>Who was there?</label><div className="form-grid">{people.map((p,i)=><label key={i}>Person {i+1}<input className="input" value={p} aria-label={`Person ${i+1} name`} onChange={x=>{setPeople(people.map((n,j)=>j===i?x.target.value:n));setClaims({});}} placeholder="Name"/></label>)}</div><button className="text-link" onClick={()=>resize(people.length+1)}><Plus size={14}/>Add person</button>
 <label>Who paid?<select className="input" value={payerIndex} onChange={x=>setPayerIndex(Number(x.target.value))}>{people.map((p,i)=><option key={i} value={i}>{p.trim()?p.trim()===currentUser?`Me (${p.trim()})`:p.trim():`Person ${i+1}`}</option>)}</select></label>
 <label>How do you think this should be split?<select className="input" value={preference} onChange={x=>setPreference(x.target.value)}><option value="infer">Let Owedience figure it out from the context</option><option value="equal">Everyone equally</option><option value="known_consumption">I already know roughly who had what</option><option value="custom">Custom / I’ll explain</option></select></label>
 {preference!=='infer'&&<details className="input-details"><summary>Have a rough split in mind? <small>Optional</small><ChevronDown size={14}/></summary><p className="muted">This is a suggestion. Owedience will compare it with the bill and context.</p>{names.map(p=><label className="rough-row" key={p}><span>{p}</span><input className="input" aria-label={`Rough share for ${p}`} inputMode="decimal" placeholder="Not sure" value={rough[p]||''} onChange={x=>setRough({...rough,[p]:x.target.value})}/></label>)}</details>}
 <label>Anything Owedience should know?<textarea className="input" value={context} onChange={x=>setContext(x.target.value)} placeholder="Who shared what? Any agreements about the cost? A natural explanation is enough." rows={3}/></label>
 <div className="input-file-row"><button className={recording?'button recording':'button'} disabled={busy} onClick={record}><Mic size={15}/>{recording?'Stop recording':'Record a voice note'}</button><button className="icon-button" aria-label="Upload a voice note" onClick={()=>voiceRef.current?.click()}><Upload size={17}/></button><input hidden type="file" accept="audio/*" ref={voiceRef} onChange={x=>{const file=x.target.files?.[0];if(file)upload(file,'voice');x.target.value='';}}/>{voice&&<span><small>{voice.filename}</small><button className="icon-button" aria-label="Remove voice note" onClick={()=>setVoice(null)}><X size={14}/></button></span>}</div>{voice&&<small className="muted">A reviewed transcription is needed before a voice note changes anyone’s share.</small>}
 {!!items.length&&!!names.length&&<details className="input-details"><summary>Prefer tapping who had what? <small>Optional</small><ChevronDown size={14}/></summary><p className="muted">Skip any item you’re unsure about. Owedience can ask later.</p>{items.map((item,i)=>{const claim=claims[i]||{consumers:[],sharing:'unsure',amounts:{},percentages:{}};return <div className="assignment-item" key={i}><strong>{item.description||`Item ${i+1}`}</strong><p className="muted">Who had this?</p><div className="assignment-chips">{names.map(p=><button className={'button '+(claim.consumers.includes(p)?'selected':'')} key={p} onClick={()=>updateClaim(i,{consumers:claim.consumers.includes(p)?claim.consumers.filter(n=>n!==p):[...claim.consumers,p]})}>{claim.consumers.includes(p)?'✓ ':''}{p}</button>)}<button className={'button '+(!claim.consumers.length?'selected':'')} onClick={()=>updateClaim(i,{consumers:[],sharing:'unsure',amounts:{},percentages:{}})}>Not sure</button></div>{!!claim.consumers.length&&<><label>How was this shared?<select className="input" value={claim.sharing} onChange={x=>updateClaim(i,{sharing:x.target.value})}><option value="unsure">Not sure — let Owedience work it out</option><option value="equal">Equally among selected people</option><option value="amounts">Different amounts</option><option value="percentages">Different percentages</option></select></label>{['amounts','percentages'].includes(claim.sharing)&&claim.consumers.map(p=><label className="rough-row" key={p}><span>{p}</span><input className="input" aria-label={`${item.description||'Item'} ${claim.sharing} for ${p}`} inputMode="decimal" placeholder={claim.sharing==='percentages'?'%':'Amount'} value={claim.sharing==='amounts'?claim.amounts[p]||'':claim.percentages[p]||''} onChange={x=>updateClaim(i,claim.sharing==='amounts'?{amounts:{...claim.amounts,[p]:x.target.value}}:{percentages:{...claim.percentages,[p]:x.target.value}})}/></label>)}</>}</div>})}</details>}
 <details className="input-details"><summary>Any other detail? <small>Optional</small><ChevronDown size={14}/></summary><p className="muted">Tips, tax or service charges, someone paying only part, an earlier repayment, something not being shared, or an amount you’re covering yourself.</p><textarea className="input" value={extra} onChange={x=>setExtra(x.target.value)} placeholder="Anything else that could affect a share…" rows={3}/></details>
 <button className="button primary full" disabled={busy||recording} onClick={save}>{busy?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>}Let Owedience sort it</button>
 </Modal>;
}
