import React, {useState,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowDownLeft,ArrowRight,Plus,Check,ChevronRight,ChevronLeft,MessageCircle,Mic,Activity,Home,Receipt,Settings,FlaskConical,ShieldCheck,X,Send,Upload,Download,Clock,Users,Leaf,AlertCircle,LoaderCircle} from 'lucide-react';
import {api,post} from './api';
import type {Episode,Obligation,SimulationEpisode,Policy} from './types';
import './styles.css';
import './components/input.css';
import {NewExpense} from './components/NewExpense';
import {FollowUp} from './components/FollowUp';

const labels:Record<string,string> = {DETECTED:'Ready to get started',UNDERSTANDING:'Putting the expense together',NEEDS_CLARIFICATION:'I need one detail',READY_TO_RECONCILE:'Working out everyone’s share',INCONSISTENT:'The receipt needs checking',AWAITING_CONFIRMATION:'Waiting for everyone to confirm',PARTIALLY_DISPUTED:'One part needs sorting out',CONFIRMED:'Ready to settle',ACTIVE:'Settling up',PARTIALLY_PAID:'Partly paid',ESCALATED:'Over to you',RECONCILED:'All sorted',CLOSED:'Settled'};
const lineLabels:Record<string,string> = {UNCONFIRMED:'Needs your okay',CONFIRMED:'Ready to settle',ACTIVE:'Waiting for payment',PARTIALLY_PAID:'Partly paid',PAID:'Paid',DISPUTED:'Paused',WAIVED:'Waived · let go'};
const money=(n:number,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:n%100?2:0}).format(n/100);
const when=(s:string)=>new Date(s).toLocaleString('en-IN',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const avatar=(name:string)=>name.slice(0,1).toUpperCase();

function App(){
 const [path,setPath]=useState(location.pathname); const [routeSearch,setRouteSearch]=useState(location.search); const [episodes,setEpisodes]=useState<Episode[]>([]); const [actor,setActor]=useState(localStorage.getItem('actor')||'');
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [modal,setModal]=useState<'new'|'preferences'|null>(null);
 const selectedId=path.startsWith('/expense/')?path.split('/')[2]:new URLSearchParams(routeSearch).get('episode');
 const selected=episodes.find(e=>e.id===selectedId)||episodes[0];
 const refresh=useCallback(async()=>{try{const rows=await api<Episode[]>('/episodes');setEpisodes(rows);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,4000);const listener=()=>{setPath(location.pathname);setRouteSearch(location.search);};window.addEventListener('popstate',listener);return()=>{clearInterval(timer);window.removeEventListener('popstate',listener);};},[refresh]);
 const go=(to:string)=>{history.pushState({},'',to);setPath(to.split('?')[0]);setRouteSearch(location.search);window.scrollTo(0,0);};
 const me=path.startsWith('/expense/')&&selected?(selected.participants.includes(actor)?actor:selected.payer):(actor||selected?.payer||'');const people=[...new Set(episodes.flatMap(e=>e.participants))];
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const message=(e:Episode,text:string,intent?:string,ids?:string[])=>act(()=>post(`/episodes/${e.id}/messages`,{type:'human_message',actor:me,origin:'consumer',content:text,intent:intent||null,obligation_ids:ids||[]}));
 const sample=()=>act(async()=>{const e=await post<Episode>('/simulation/seed/restaurant');go('/expense/'+e.id);});
 const sim=path==='/simulation';
 return <div className={sim?'app simulation-app':'app'}>
  <aside className="sidebar"><a className="brand" href="/" onClick={e=>{e.preventDefault();go('/');}}><span className="brand-mark"><Leaf size={22}/></span>owedience<span className="brand-dot">.</span></a><p className="brand-note">Shared expenses, understood.</p>
   <nav>{[[Home,'/','Overview'],[Receipt,'/expenses','Your expenses'],[Activity,'/activity','Activity']] .map(([Icon,to,label])=><button key={String(to)} className={path===to?'nav-link active':'nav-link'} onClick={()=>go(String(to))}>{React.createElement(Icon as typeof Home,{size:19})}{String(label)}</button>)}</nav>
   <div className="sidebar-bottom"><div className="trust-note"><ShieldCheck size={20}/><div>Never guess.<br/>Never overstep.</div></div><button className={sim?'nav-link active':'nav-link'} onClick={()=>go('/simulation'+(selected?'?episode='+selected.id:''))}><FlaskConical size={18}/>Simulation console<ArrowUpRight size={15}/></button><div className="profile"><span className="avatar small">{me?avatar(me):'O'}</span><div><small>Viewing as</small>{people.length?<select aria-label="Viewing as" value={me} onChange={e=>{setActor(e.target.value);localStorage.setItem('actor',e.target.value);}}>{people.map(p=><option key={p}>{p}</option>)}</select>:<strong>You</strong>}</div><Settings size={17}/></div></div>
  </aside>
  <main><header className="topbar"><span>{sim?'The outside world → Owedience':path.startsWith('/expense/')?'Your expense':path==='/activity'?'Your activity':'A little less to keep track of.'}</span><div><select className="mobile-actor" aria-label="Your viewing identity" value={me} onChange={e=>{setActor(e.target.value);localStorage.setItem('actor',e.target.value);}}>{people.map(p=><option key={p}>{p}</option>)}</select><span className="safe-tag"><span/> {busy?'Working on it':'Your money, your say'}</span><button className="button primary small-button" onClick={()=>setModal('new')}><Plus size={16}/>New expense</button></div></header>
   {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/>{error}<button aria-label="Dismiss" onClick={()=>setError('')}><X size={16}/></button></div>}
   {busy&&<div className="working-bar"><LoaderCircle size={14} className="spin"/>Owedience is working through the expense. Your evidence is saved as it goes.</div>}
   {sim?<Simulation episodes={episodes} selected={selected} busy={busy} act={act} go={go}/>:
   path.startsWith('/expense/')&&selected?<Expense e={selected} me={me} busy={busy} message={message} act={act} go={go} preferences={()=>setModal('preferences')}/>:
   path==='/activity'?<div className="content"><p className="eyebrow">THE LITTLE THINGS, TAKEN CARE OF</p><h1>Every step, in the open.</h1><div className="card activity-list">{episodes.flatMap(e=>e.messages.map(m=>({...m,title:e.title}))).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).map((m,i)=><div className="timeline-item" key={i}><span className="timeline-dot"/><div><strong>{m.speaker}</strong><p>{m.message}</p><small>{m.title} · {when(m.timestamp)}{m.recipient?' · For '+m.recipient:''}{m.delivery_status==='SIMULATED_DELIVERY'?' · Simulated delivery':''}</small></div></div>)}{!episodes.length&&<Empty text="Your expense updates will appear here."/>}</div></div>:
   <Overview episodes={episodes} me={me} go={go} sample={sample} newExpense={()=>setModal('new')} onlyExpenses={path==='/expenses'}/>}
  </main>
  <nav className="mobile-nav"><button onClick={()=>go('/')}><Home size={20}/>Home</button><button onClick={()=>go('/expenses')}><Receipt size={20}/>Expenses</button><button onClick={()=>go('/activity')}><Activity size={20}/>Activity</button><button onClick={()=>go('/simulation')}><FlaskConical size={20}/>Simulation</button></nav>
  {modal==='new'&&<NewExpense Modal={Modal} currentUser={me} close={()=>setModal(null)} busy={busy} submit={body=>act(async()=>{const e=await post<Episode>('/episodes',body);setActor(e.payer);localStorage.setItem('actor',e.payer);setModal(null);go('/expense/'+e.id);})}/>}
  {modal==='preferences'&&selected&&<Preferences e={selected} me={me} close={()=>setModal(null)} save={policy=>act(async()=>{await api(`/episodes/${selected.id}/preferences`,{method:'PUT',body:JSON.stringify({actor:me,policy})});setModal(null);})}/>}
 </div>;
}
function Empty({text}:{text:string}){return <div className="empty"><Leaf size={28}/><p>{text}</p></div>;}
function Overview({episodes,me,go,sample,newExpense,onlyExpenses}:{episodes:Episode[];me:string;go:(s:string)=>void;sample:()=>void;newExpense:()=>void;onlyExpenses:boolean}){
 const owed=episodes.flatMap(e=>e.obligations.filter(o=>o.creditor===me&&o.status!=='UNCONFIRMED'&&o.status!=='DISPUTED').map(o=>({o,c:e.currency})));
 const owing=episodes.flatMap(e=>e.obligations.filter(o=>o.debtor===me&&o.status!=='UNCONFIRMED'&&o.status!=='DISPUTED').map(o=>({o,c:e.currency})));
 const currencies=[...new Set(episodes.map(e=>e.currency))];const balances=(rows:typeof owed)=>currencies.length?currencies.map(c=>({c,n:rows.filter(x=>x.c===c).reduce((s,x)=>s+x.o.amount_remaining,0)})):[{c:'INR',n:0}];
 const needed=episodes.filter(e=>e.obligations.some(o=>o.creditor===me&&o.reminder_approval&&!o.reminder_approval.approved_at)||e.clarifications.some(q=>q.status==='OPEN'&&q.recipient===me)||e.obligations.some(o=>o.debtor===me&&o.status==='UNCONFIRMED'));
 return <div className="content"><div className="page-heading"><div><p className="eyebrow">A FAIR SHARE. A CLEAR HEAD.</p><h1>{onlyExpenses?'Your expenses.':`Hello${me?', '+me:''}.`}<br/>{!onlyExpenses&&<span>Let’s keep things easy.</span>}</h1><p className="subtitle">{onlyExpenses?'From the first detail to the last payment.':'The shared moments are yours. We’ll help with the settling up.'}</p></div><div className="illustration" aria-hidden="true"><div className="receipt-art"><span>SHARED, SORTED</span><i/><i/><i/><b><Check size={22}/> all fair</b></div><div className="coin-art">₹</div><span className="spark s1">✦</span><span className="spark s2">✦</span></div></div>
 {!onlyExpenses&&<><div className="summary-grid"><div className="balance-card green"><div><span className="round-icon"><ArrowDownLeft size={20}/></span><span>You’re owed</span></div>{balances(owed).map(x=><h2 key={x.c}>{money(x.n,x.c)}</h2>)}<p>{new Set(owed.filter(x=>x.o.amount_remaining).map(x=>x.o.debtor)).size} people still settling up</p></div><div className="balance-card"><div><span className="round-icon neutral"><ArrowUpRight size={20}/></span><span>You owe</span></div>{balances(owing).map(x=><h2 key={x.c}>{money(x.n,x.c)}</h2>)}<p>{owing.some(x=>x.o.amount_remaining)?'Your confirmed shares, ready when you are.':'You’re all caught up. Nice.'}</p></div><div className="balance-card promise"><ShieldCheck size={28}/><h3>Fair doesn’t always<br/>mean equal.</h3><p>Everyone’s share follows what actually happened.</p></div></div>
 <div className="section-heading"><h2>Needs you <span className="count">{needed.length}</span></h2><span>Just the details that matter</span></div>{needed.length?<div className="needs-grid">{needed.map(e=><button className="need-card" key={e.id} onClick={()=>go('/expense/'+e.id)}><div className="need-top"><span className="expense-icon"><Receipt size={21}/></span><span className="pill amber">Your turn</span></div><h3>{e.title}</h3><p>{money(e.total,e.currency)} · {e.participants.length} people</p><div className="question-preview"><MessageCircle size={16}/><span>{e.clarifications.find(q=>q.status==='OPEN')?.message||e.obligations.find(o=>o.creditor===me&&o.reminder_approval)?.reminder_approval?.message||'Does your share look right?'}</span></div><span className="text-link">Take a look <ArrowRight size={16}/></span></button>)}</div>:<div className="quiet-card"><Check size={20}/><div><strong>Nothing needs you right now.</strong><p>We’ll bring the next useful question here.</p></div></div>}</>}
 <div className="section-heading"><h2>{onlyExpenses?'All expenses':'Your shared expenses'}</h2><button className="text-link" onClick={newExpense}>Add an expense <Plus size={15}/></button></div><div className="card expense-list">{episodes.map(e=><button className="expense-row" key={e.id} onClick={()=>go('/expense/'+e.id)}><span className="expense-icon"><Receipt size={20}/></span><div className="expense-row-title"><strong>{e.title}</strong><small>Paid by {e.payer} · {e.participants.length} people · {new Date(e.created_at).toLocaleDateString('en-IN',{month:'short',day:'numeric'})}</small></div><div className="expense-row-amount"><strong>{money(e.total,e.currency)}</strong><span className={e.status==='CLOSED'?'status settled':'status'}>{e.status==='CLOSED'&&<Check size={12}/>} {labels[e.status]}</span></div><ChevronRight size={17}/></button>)}{!episodes.length&&<div className="onboarding"><span className="expense-icon"><Users size={25}/></span><h3>A shared moment starts here.</h3><p>Add a dinner, a trip, groceries, or anything you paid for together.<br/>Tell Owedience what happened. It will ask for what’s missing.</p><div className="button-row"><button className="button primary" onClick={newExpense}>Add your first expense <Plus size={16}/></button><button className="button" onClick={sample}>Try the sample dinner</button></div><small>The sample supplies expense facts. Owedience works out what to do.</small></div>}</div><footer className="page-footer"><Leaf size={14}/> Less awkward. More understood.<span>You always have the final say.</span></footer></div>;
}
function Expense({e,me,busy,message,act,go,preferences}:{e:Episode;me:string;busy:boolean;message:(e:Episode,text:string,intent?:string,ids?:string[])=>Promise<void>;act:(fn:()=>Promise<unknown>)=>Promise<void>;go:(s:string)=>void;preferences:()=>void}){
 const [text,setText]=useState('');const [dispute,setDispute]=useState<Obligation[]|null>(null);const [checked,setChecked]=useState<string[]>([]);const [recording,setRecording]=useState(false);
 const recorder=React.useRef<MediaRecorder|null>(null); const audioRef=React.useRef<HTMLInputElement>(null);
 const sendAudio=async(file:Blob,name:string)=>{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});return post(`/episodes/${e.id}/audio`,{type:'audio',actor:me,origin:'consumer',content:name,audio_base64:data,mime_type:file.type||'audio/webm'});};
 const voice=()=>act(async()=>{if(recording){recorder.current?.stop();setRecording(false);return;}const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=x=>chunks.push(x.data);r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());act(()=>sendAudio(new Blob(chunks,{type:r.mimeType}),'Voice note'));};r.start();setRecording(true);});
 const ask=e.clarifications.find(q=>q.status==='OPEN');const outstanding=e.obligations.reduce((s,o)=>s+o.amount_remaining,0);const paid=e.obligations.reduce((s,o)=>s+o.amount_paid,0);
 const submit=async()=>{if(!text.trim())return;await message(e,text);setText('');};
 return <div className="content expense-content"><button className="back-link" onClick={()=>go('/')}><ChevronLeft size={16}/>All expenses</button><div className="expense-hero"><div><p className="eyebrow">A SHARED MOMENT</p><h1>{e.title}</h1><p>Paid by <strong>{e.payer}</strong> · {when(e.created_at)}</p><span className="pill">{labels[e.status]}</span></div><div><h2>{money(e.total,e.currency)}</h2><small>Total expense</small></div></div>
 <div className="people-bar"><span>Who’s involved</span><div>{e.participants.map((p,i)=><span className="person-chip" key={p}><span className={'avatar tone-'+i%4}>{avatar(p)}</span>{p}{p===e.payer&&<small>paid</small>}</span>)}</div></div>
 {e.agent_notice&&<div className="notice"><Clock size={20}/><p>{e.agent_notice}</p><button className="text-link" disabled={busy} onClick={()=>act(()=>post(`/episodes/${e.id}/continue`))}>Try again <ArrowRight size={14}/></button></div>}
 {e.status==='CLOSED'&&<div className="completion"><Check size={24}/><div><h3>All sorted.</h3><p>Everyone’s share is resolved. No more reminders will be sent.</p></div></div>}
 {e.attachments?.length>0&&<div className="notice"><Receipt size={18}/><div><strong>Files you shared</strong><p>{e.attachments.map(a=><a key={a.id} href={`/api/episodes/${e.id}/attachments/${a.id}`} className="text-link" style={{marginRight:12}}>{a.filename} <Download size={12}/></a>)}</p><small>Receipts are saved as evidence. Shares use supplied items and reviewed context.</small></div></div>}
 <div className="expense-columns"><div><section className="card"><div className="card-heading"><h2>What Owedience understood</h2><Leaf size={18}/></div><p className="muted card-subtitle">A little context makes a fairer share.</p>{e.components.map(c=><div className="component-row" key={c.id}><div><strong>{c.description}</strong><p>{c.dispute_status!=='CLEAR'?'This part needs checking':c.consumers.length?c.consumers.join(' + '):'Who shared this? Still to be understood.'}</p></div><strong>{money(c.amount,e.currency)}</strong></div>)}</section>
 <section className="card conversation"><div className="card-heading"><h2>{ask?'One useful question':'Tell us what happened'}</h2><MessageCircle size={18}/></div>{ask?<div className="agent-question"><span className="agent-avatar"><Leaf size={17}/></span><p>{ask.message}</p></div>:<p className="muted">Add context, clear up a detail, or let us know if something feels off.</p>}
 <div className="message-input"><textarea aria-label="Expense context or answer" value={text} onChange={x=>setText(x.target.value)} placeholder={ask?'Your answer…':'Who shared what?'} rows={3}/><div><button className={recording?'icon-button recording':'icon-button'} aria-label={recording?'Stop recording':'Record voice note'} onClick={voice} disabled={busy||e.status==='CLOSED'}><Mic size={18}/>{recording?'Stop':'Speak'}</button><button className="icon-button" onClick={()=>audioRef.current?.click()} aria-label="Upload voice note" disabled={busy||e.status==='CLOSED'}><Upload size={17}/></button><input hidden ref={audioRef} type="file" accept="audio/*" onChange={x=>{const file=x.target.files?.[0];if(file){act(()=>sendAudio(file,'Voice note: '+file.name));x.target.value='';}}}/><button className="button primary small-button" disabled={busy||!text.trim()||!e.participants.includes(me)||e.status==='CLOSED'} onClick={submit}>Send <Send size={14}/></button></div></div><small className="muted">Voice notes wait for a reviewed transcription before changing anyone’s share.</small></section>
 <section className="card"><div className="card-heading"><h2>Activity</h2><Clock size={18}/></div>{e.messages.slice(-5).map((m,i)=><div className="mini-activity" key={i}><span className="timeline-dot"/><div><strong>{m.speaker}</strong><p>{m.message}</p><small>{when(m.timestamp)}{m.recipient?' · For '+m.recipient:''}{m.delivery_status==='SIMULATED_DELIVERY'?' · Simulated delivery':''}</small></div></div>)}{!e.messages.length&&<p className="muted">The expense is saved. Add context to get started.</p>}</section></div>
 <div><section className="card shares-card"><div className="card-heading"><h2>Everyone’s share</h2><Users size={18}/></div>{!e.allocations.length?<Empty text="Your shares will appear when the important details are clear."/>:e.participants.map((p,i)=>{const rows=e.obligations.filter(o=>o.debtor===p);const share=e.allocations.filter(a=>a.participant===p).reduce((s,a)=>s+a.amount,0);if(!share)return null;return <div className="person-share" key={p}><div className="share-person"><span className={'avatar tone-'+i%4}>{avatar(p)}</span><div><strong>{p}</strong><small>{p===e.payer?'Already covered their own share':`To ${e.payer}`}</small></div><strong>{money(share,e.currency)}</strong></div><div className="share-breakdown">{e.allocations.filter(a=>a.participant===p).map(a=>{const o=rows.find(o=>o.component_id===a.component_id);return <div key={a.component_id}><span title={a.reason}>{e.components.find(c=>c.id===a.component_id)?.description}{o&&<small className={o.status==='DISPUTED'?'paused':''}>{lineLabels[o.status]}</small>}</span><span>{money(a.amount,e.currency)}{o?.amount_paid? <small>{money(o.amount_paid,e.currency)} paid · {money(o.amount_remaining,e.currency)} left</small>:null}</span></div>})}</div><details className="input-details"><summary>Why this amount?</summary>{e.allocations.filter(a=>a.participant===p).map(a=><p className="muted" key={a.component_id}>{a.reason}</p>)}</details>{rows.some(o=>o.status==='UNCONFIRMED')&&p===me&&<button className="button primary full" disabled={busy} onClick={()=>message(e,'My selected shares look right.','CONFIRM',rows.filter(o=>o.status==='UNCONFIRMED').map(o=>o.id))}><Check size={16}/>Looks right</button>}
 {rows.some(o=>!['PAID','WAIVED'].includes(o.status))&&(p===me||me===e.payer)&&<div className="share-actions"><button onClick={()=>{setDispute(rows.filter(o=>!['PAID','WAIVED'].includes(o.status)));setChecked([]);setText('');}}>Something’s wrong</button></div>}
 {rows.some(o=>o.status==='DISPUTED')&&(me===p||me===e.payer)&&<button className="text-link" disabled={busy} onClick={()=>message(e,'I agree to resolve the selected disputed shares at the existing amounts.','RESOLVE_DISPUTE',rows.filter(o=>o.status==='DISPUTED').map(o=>o.id))}>I agree with this amount</button>}
 {rows.map(o=><FollowUp key={o.id} e={e} o={o} me={me} busy={busy} act={act} Modal={Modal}/>)}
 {e.settlement_requests.filter(r=>r.debtor===p).map(r=><div className="settlement-note" key={r.id}><span>{r.obligation_ids.every(id=>rows.find(o=>o.id===id)?.amount_remaining===0)?'Share resolved':'Payment request ready'}{r.mode==='wizard'?' · Practice mode':''}</span>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">Settle up <ArrowUpRight size={13}/></a>}</div>)}
 </div>})}</section>
 {!!e.obligations.length&&<section className="card settlement-summary"><h2>Settling up</h2><div><span>Already paid</span><strong>{money(paid,e.currency)}</strong></div><div><span>Still to resolve</span><strong>{money(outstanding,e.currency)}</strong></div><p className="muted">Only shares people have agreed to can enter settlement.</p><button className="text-link" disabled={busy||e.status==='CLOSED'} onClick={()=>act(()=>post(`/episodes/${e.id}/continue`))}>Let Owedience continue <ArrowRight size={15}/></button></section>}
 <div className="gentle-note"><ShieldCheck size={20}/><p>Your shares need your okay.<br/>Silence never counts as agreement.</p></div>{me===e.payer&&e.status!=='CLOSED'&&<button className="text-link preference-link" onClick={preferences}><Settings size={16}/>Reminder preferences</button>}</div></div>
 {dispute&&<Modal title="Let’s sort out just that part." close={()=>setDispute(null)}><p className="muted">Choose the parts you disagree with. The other shares can continue.</p>{dispute.map(o=><label className="checkbox-row" key={o.id}><input type="checkbox" checked={checked.includes(o.id)} onChange={x=>setChecked(x.target.checked?[...checked,o.id]:checked.filter(id=>id!==o.id))}/><span>{e.components.find(c=>c.id===o.component_id)?.description}</span><strong>{money(o.amount,e.currency)}</strong></label>)}<textarea className="input" placeholder="What needs clearing up?" value={text} onChange={x=>setText(x.target.value)}/><button className="button primary full" disabled={busy||!checked.length||!text.trim()} onClick={async()=>{await message(e,text,'DISPUTE',checked);setDispute(null);setText('');}}>Pause these parts</button></Modal>}
 </div>;
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onClick={close}><section className="modal card" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={close} aria-label="Close"><X size={20}/></button><h2>{title}</h2>{children}</section></div>;}
function Preferences({e,me,close,save}:{e:Episode;me:string;close:()=>void;save:(p:Policy)=>Promise<void>}){const [p,setP]=useState(e.reminder_policy);return <Modal title="Follow-ups, on your terms." close={close}><label className="checkbox-row"><input type="checkbox" checked={p.enabled} onChange={x=>setP({...p,enabled:x.target.checked})}/>Enable checks for shares I have individually authorized</label><p className="muted">You decide who Owedience is allowed to follow up with. Choose frequency, limits and approval on each person’s share. This switch cannot authorize a share.</p><button className="button primary full" disabled={me!==e.payer} onClick={()=>save(p)}>Save preferences</button></Modal>;}

function Simulation({episodes,selected,busy,act,go}:{episodes:Episode[];selected:Episode|undefined;busy:boolean;act:(fn:()=>Promise<unknown>)=>Promise<void>;go:(s:string)=>void}){
 const [state,setState]=useState<SimulationEpisode|null>(null);const [config,setConfig]=useState<{llm_configured:boolean;provider:string;model:string;connector_mode:string;rules:Record<string,string>}|null>(null);const [simError,setSimError]=useState('');const [token,setToken]=useState(sessionStorage.getItem('simulationToken')||'');
 const [kind,setKind]=useState('human_message');const [actor,setActor]=useState(selected?.payer||'');const [content,setContent]=useState('');const [reference,setReference]=useState('');const [amount,setAmount]=useState('');const [paymentId,setPaymentId]=useState('');const [verified,setVerified]=useState(true);const [connector,setConnector]=useState('gnani');const [operation,setOperation]=useState('transcribe_audio');const [requestKey,setRequestKey]=useState('');const [result,setResult]=useState('{}');const [timestamp,setTimestamp]=useState(new Date().toISOString());const [recovered,setRecovered]=useState(false);const [disputeIds,setDisputeIds]=useState<string[]>([]);
 const refresh=useCallback(async()=>{try{const c=await api<typeof config>('/simulation/config');setConfig(c);if(selected){setState(await api<SimulationEpisode>('/simulation/episodes/'+selected.id));}setSimError('');}catch(e){setSimError((e as Error).message);}},[selected?.id]);
 useEffect(()=>{refresh();const t=setInterval(refresh,3000);return()=>clearInterval(t);},[refresh]);useEffect(()=>{setActor(selected?.payer||'');setState(null);},[selected?.id]);
 const inject=()=>act(async()=>{if(!selected)return;const base={type:kind,actor:actor||'External world',origin:'wizard'};let event:unknown;
  if(kind==='dispute'){if(!disputeIds.length||!content.trim())throw new Error('Choose the disputed components and provide the human’s statement.');event={...base,type:'human_message',content,intent:'DISPUTE',obligation_ids:disputeIds};}
  else if(kind==='human_message')event={...base,content};
  else if(kind==='audio')event={...base,content};
  else if(kind==='payment_reference')event={...base,payment_id:paymentId,debtor:actor,creditor:selected.payer,currency:selected.currency,reference,verified};
  else if(kind==='payment'){if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('Use an amount with up to two decimals.');const [a,b='']=amount.split('.');event={...base,payment_id:paymentId,amount:Number(a)*100+Number(b.padEnd(2,'0')),debtor:actor,creditor:selected.payer,currency:selected.currency,reference:reference||null,verified};}
  else if(kind==='clock')event={...base,timestamp};
  else if(kind==='connector_failure')event={...base,connector,content,recovered};
  else if(kind==='shipment')event={...base,content,reference};
  else event={...base,connector,operation,request_key:requestKey,result:JSON.parse(result)};
  await post(`/simulation/episodes/${selected.id}/events`,event);setContent('');await refresh();});
 const download=async(format:string)=>{if(!selected)return;const r=await fetch(`/api/simulation/episodes/${selected.id}/audit?format=${format}`,{headers:{'X-Simulation-Token':token}});if(!r.ok)throw new Error('Audit export requires simulation access.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`owedience-audit.${format}`;a.click();URL.revokeObjectURL(url);};
 return <div className="simulation-content"><div className="sim-heading"><div><p className="eyebrow">COMPETITION OBSERVATORY</p><h1>Owedience simulation<span className="pill">External rails: {config?.connector_mode||'…'}</span></h1><p>Supply facts. Watch the agent decide. Every consequential action leaves a trace.</p></div><div className="button-row"><button className="button" disabled={busy} onClick={()=>act(async()=>{const e=await post<Episode>('/simulation/seed/restaurant');go('/simulation?episode='+e.id);})}>Load dinner facts</button><button className="button" disabled={busy} onClick={()=>act(async()=>{const e=await post<Episode>('/simulation/seed/cab');go('/simulation?episode='+e.id);})}>Load cab facts</button></div></div>
 <div className="sim-config"><label>Episode<select className="input" value={selected?.id||''} onChange={x=>go('/simulation?episode='+x.target.value)}><option value="" disabled>Choose an expense</option>{episodes.map(e=><option key={e.id} value={e.id}>{e.title} · {e.id.slice(-6)}</option>)}</select></label><div><small>Agent connection</small><strong>{config?.llm_configured?'Configured':'Awaiting configuration'}</strong><span>{config?.provider} · {config?.model}</span></div><label>Simulation access token<input className="input" type="password" value={token} placeholder="Only if configured" onChange={x=>{setToken(x.target.value);sessionStorage.setItem('simulationToken',x.target.value);}} onBlur={refresh}/></label></div>
 {simError&&<div className="notice"><AlertCircle size={18}/>{simError}</div>}{config&&!config.llm_configured&&<div className="notice"><Settings size={20}/><div><strong>Connect an LLM to start autonomous analysis.</strong><p>Copy .env.example to .env, configure the selected provider’s API key and LLM_MODEL, then restart the backend. No rule-based stand-in runs without a model.</p></div></div>}
 {state?<><div className="sim-state-strip"><strong>{state.title}</strong><span>{state.status}</span><span>{money(state.total,state.currency)}</span><span>Paid by {state.payer}</span><span>{when(state.clock)}</span><button className="text-link" onClick={()=>go('/expense/'+state.id)}>Consumer view <ArrowUpRight size={14}/></button></div>
 <div className="sim-columns"><section className="card sim-panel"><div className="card-heading"><h2>01 · External world</h2><span className="count">{state.evidence.length}</span></div><p className="muted">Facts received, with their source and verification state.</p>{state.evidence.map(ev=><details className="evidence-item" key={ev.id} open={state.evidence.indexOf(ev)===state.evidence.length-1}><summary><strong>{ev.type.replaceAll('_',' ')}</strong><span className={'pill '+(ev.verification_status==='AMBIGUOUS'?'amber':'')}>{ev.verification_status}</span></summary><small>{ev.source} · {ev.origin} · {ev.connector}<br/>{when(ev.timestamp)}</small><p>{ev.content}</p><div className="technical-id">{ev.id}{ev.derived_from.length?' ← '+ev.derived_from.join(', '):''}</div></details>)}</section>
 <section className="card sim-panel"><div className="card-heading"><h2>02 · Episode & ledger</h2><Receipt size={18}/></div><p className="muted">The same persistent state used by the consumer product.</p>{state.components.map(c=><div className="sim-component" key={c.id}><strong>{c.description}<span>{money(c.amount,state.currency)}</span></strong><p>{c.consumers.length?c.consumers.join(' + '):'Consumers not established'}</p><small>{c.dispute_status} · {c.id}</small></div>)}<h3 className="sim-subtitle">Component obligations</h3>{state.obligations.map(o=><div className="sim-obligation" key={o.id}><strong>{o.debtor} → {o.creditor}<span>{money(o.amount,state.currency)}</span></strong><p>{state.components.find(c=>c.id===o.component_id)?.description} · {o.status}</p><small>{money(o.amount_paid,state.currency)} paid · {money(o.status==='WAIVED'?0:o.amount-o.amount_paid,state.currency)} left</small><code>{o.id}</code><h4>Follow-up authorization</h4><small>{o.follow_up_authorized} · Authorized by: {o.authorized_by||'Nobody'}<br/>For: {o.debtor} · {state.components.find(c=>c.id===o.component_id)?.description}<br/>Remaining: {money(o.amount_remaining,state.currency)}</small><h4>Reminder policy</h4><small>Frequency: {o.follow_up_policy.minimum_interval_hours} hours · Maximum: {o.follow_up_policy.maximum}<br/>Approval: {o.follow_up_policy.reminder_approval_mode}<br/>Quiet: {o.follow_up_policy.quiet_start}–{o.follow_up_policy.quiet_end}<br/>Sent: {o.reminder_count} · Next: {o.next_check_at?when(o.next_check_at):'Stopped / awaiting authorization'}<br/>{o.next_check_at&&<code>{o.next_check_at}</code>}{o.reminder_approval?'Creditor approval '+(o.reminder_approval.approved_at?'granted':'pending'):o.reminder_eligibility.reason}</small>{o.reminder_history.map((r,i)=><p key={i}>{String(r.connector.status)} · {when(r.timestamp)}<br/>{r.message}</p>)}</div>)}{!state.obligations.length&&<Empty text="No supported ledger yet."/>}<h3 className="sim-subtitle">Payment references</h3>{state.settlement_requests.map(r=><div className="reference-item" key={r.id}><strong>{r.debtor} · {money(r.amount,state.currency)}</strong><code>{r.reference}</code><small>{r.mode} · {r.reminders} reminders</small></div>)}{state.payments.map(p=><div className="reference-item" key={p.id}><strong>{p.id} · {money(p.amount,state.currency)}</strong><small>{p.status} · {p.reference||'No reliable reference'}</small></div>)}</section>
 <section className="card sim-panel decisions"><div className="card-heading"><h2>03 · Agent activity</h2><Activity size={18}/></div><p className="muted">Concise rationale and tool observations. Private reasoning is never collected.</p>{state.audit_events.map(a=><details className={'decision-item '+(!a.accepted?'rejected':'')} key={a.id}><summary><span className="decision-dot"/><div><strong>{a.decision}</strong><small>{when(a.timestamp)} · {a.accepted?'Recorded':'Rejected / paused'}</small></div><ChevronRight size={14}/></summary><p>{a.concise_reason}</p><div className="rule-tags">{a.rule_ids.map(r=><span key={r} title={config?.rules[r]}>{r}</span>)}</div><dl><dt>Source</dt><dd>{a.input_source} / {a.real_world_source} / {a.connector}</dd><dt>State</dt><dd>{a.state_before} → {a.state_after}</dd><dt>Tool</dt><dd>{a.action}</dd>{a.recipient&&<><dt>Recipient</dt><dd>{a.recipient}</dd></>}{(a.tool_response.exact_message||a.exact_message)&&<><dt>Exact message</dt><dd>{String(a.tool_response.exact_message||a.exact_message)}</dd></>}</dl><details><summary>Input / tool request / observation</summary><pre>{JSON.stringify({input:a.input_received,provider:a.provider_call,request:a.tool_request,result:a.tool_response},null,2)}</pre></details></details>)}</section></div>
 <section className="card wizard-panel"><div><p className="eyebrow">PLAY THE OUTSIDE WORLD</p><h2>Inject an external event</h2><div className="button-row"><button className="button small-button" onClick={()=>setKind('clock')}>Advance clock</button><button className="button small-button" onClick={()=>setKind('payment')}>Inject partial / full payment</button><button className="button small-button" onClick={()=>{setKind('dispute');setDisputeIds([]);}}>Inject dispute</button></div><p className="muted">No controls for agent decisions. Human messages, rail responses, payments, time and failures only.</p></div><div className="wizard-form"><label>External event<select className="input" value={kind} onChange={x=>setKind(x.target.value)}>{[['human_message','Human message'],['dispute','Human dispute · selected components'],['audio','Voice note reference'],['payment','Verified payment · partial or full'],['payment_reference','Verified payment reference'],['connector_response','Connector response'],['shipment','Shipment evidence'],['clock','Advance clock'],['connector_failure','Connector failure / recovery']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>{kind==='payment'?'Who paid?':'Speaker / source'}<select className="input" value={actor} onChange={x=>setActor(x.target.value)}>{state.participants.map(p=><option key={p}>{p}</option>)}</select></label>
 {['human_message','dispute','audio','shipment','connector_failure'].includes(kind)&&<label className="wide">{kind==='audio'?'Voice note reference (upload audio from consumer view)':'External content'}<textarea className="input" value={content} onChange={x=>setContent(x.target.value)} placeholder="Only provide what a person or external service actually said." rows={3}/></label>}
 {kind==='dispute'&&<div className="wide">{state.obligations.filter(o=>[o.debtor,o.creditor].includes(actor)&&!['PAID','WAIVED'].includes(o.status)).map(o=><label className="checkbox-row" key={o.id}><input type="checkbox" checked={disputeIds.includes(o.id)} onChange={x=>setDisputeIds(x.target.checked?[...disputeIds,o.id]:disputeIds.filter(id=>id!==o.id))}/>{o.debtor} · {state.components.find(c=>c.id===o.component_id)?.description} · {money(o.amount_remaining,state.currency)}</label>)}</div>}
 {['payment','payment_reference'].includes(kind)&&<><label>Payment ID<input className="input" value={paymentId} onChange={x=>setPaymentId(x.target.value)} placeholder="Unique receipt identifier"/></label>{kind==='payment'&&<label>Amount ({state.currency})<input className="input" value={amount} inputMode="decimal" onChange={x=>setAmount(x.target.value)}/></label>}<label className="wide">Reliable payment reference<input className="input" list="payment-refs" value={reference} onChange={x=>setReference(x.target.value)} placeholder="Paste an issued payment reference; leave empty to test ambiguity"/><datalist id="payment-refs">{state.settlement_requests.map(r=><option key={r.id} value={r.reference}>{r.debtor}</option>)}</datalist></label><label className="checkbox-row wide"><input type="checkbox" checked={verified} onChange={x=>setVerified(x.target.checked)}/>Wizard attests this money movement as verified (simulation only)</label></>}
 {kind==='shipment'&&<label>Shipment reference<input className="input" value={reference} onChange={x=>setReference(x.target.value)}/></label>}
 {kind==='clock'&&<label className="wide">External time (ISO 8601, with time zone)<input className="input" value={timestamp} onChange={x=>setTimestamp(x.target.value)}/></label>}
 {['connector_response','connector_failure'].includes(kind)&&<label>Rail<select className="input" value={connector} onChange={x=>setConnector(x.target.value)}>{['gnani','pine_labs','delhivery','messaging'].map(c=><option key={c}>{c}</option>)}</select></label>}
 {kind==='connector_failure'&&<label className="checkbox-row"><input type="checkbox" checked={recovered} onChange={x=>setRecovered(x.target.checked)}/>Connector recovered</label>}
 {kind==='connector_response'&&<><label>Requested operation<input className="input" value={operation} onChange={x=>setOperation(x.target.value)}/></label><label className="wide">Request key from the pending action<input className="input" value={requestKey} onChange={x=>setRequestKey(x.target.value)}/></label><label className="wide">Documented rail response (JSON)<textarea className="input monospace" rows={4} value={result} onChange={x=>setResult(x.target.value)}/></label><small className="wide muted">For a reviewed voice transcript: transcript, human_verified: true, and optional confidence. Review the actual audio; uncertain transcripts stay ambiguous.</small></>}
 <button className="button primary wide" disabled={busy} onClick={inject}><Send size={16}/>{busy?'Agent is evaluating…':'Inject event'}</button></div></section>
 <div className="sim-footer"><span><ShieldCheck size={17}/> Wizard events are labelled. No real payments or messages are sent.</span><div className="button-row"><button className="button" onClick={()=>act(()=>download('json'))}><Download size={15}/>Audit JSON</button><button className="button" onClick={()=>act(()=>download('csv'))}><Download size={15}/>Audit CSV</button></div></div>
 </>:<Empty text="Load sample facts or create an expense to start observing."/>}
 <details className="card rules-card"><summary>System rules · the autonomy boundary</summary>{config&&Object.entries(config.rules).map(([id,text])=><p key={id}><strong>{id}</strong>{text}</p>)}</details></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
